/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7feed0b69b98f0f3c6cbf25334d44200)
interface __BaseEnv_Env {
	MAIN_SITE: "https://omg-site-4gd.pages.dev";
	DOCS_SITE: "https://omg.latham.cloud";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAIN_SITE" | "DOCS_SITE">> {}
}
