/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 109727b15054044a76fed1f7eda3f4ac)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	LICENSING_API: Fetcher /* omg-saas */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
