/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3e20080cad80254d857fab5313fea5d5)
interface __BaseEnv_Env {
  DB: D1Database;
  ASSETS: Fetcher;
  LICENSING_API: Fetcher /* omg-saas */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
