/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3e0cb9d970a183509fe33f930385e2e8)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
