/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b8c81aa5265513ddb374adf49024e412)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DOWNLOAD_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		DOWNLOAD_RATE_LIMITER: RateLimit;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
