/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/releases/wrangler.toml --include-runtime=false workers/releases/worker-configuration.d.ts` (hash: a4ecab3debb4bea03f8dac03dc0e080f)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	ANALYTICS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		ANALYTICS_DB: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
