INSERT INTO achievement_definition (id, name, description, icon, category, requirement, points, is_hidden, sort_order) VALUES
('first_command', 'First Steps', 'Run your first OMG command', 'Rocket', 'milestone', 'commands_run >= 1', 5, 0, 1),
('getting_started', 'Getting Started', 'Run 10 commands', 'Terminal', 'milestone', 'commands_run >= 10', 10, 0, 2),
('power_user', 'Power User', 'Run 100 commands', 'Zap', 'milestone', 'commands_run >= 100', 25, 0, 3),
('command_master', 'Command Master', 'Run 1,000 commands', 'Crown', 'master', 'commands_run >= 1000', 50, 0, 4),
('cli_legend', 'CLI Legend', 'Run 10,000 commands', 'Trophy', 'master', 'commands_run >= 10000', 100, 0, 5),
('package_explorer', 'Package Explorer', 'Search for 50 packages', 'Search', 'explorer', 'packages_searched >= 50', 15, 0, 10),
('package_hunter', 'Package Hunter', 'Search for 500 packages', 'Target', 'explorer', 'packages_searched >= 500', 30, 0, 11),
('package_master', 'Package Master', 'Install 100 packages', 'Package', 'master', 'packages_installed >= 100', 40, 0, 12),
('dependency_manager', 'Dependency Manager', 'Install 500 packages', 'Box', 'master', 'packages_installed >= 500', 75, 0, 13),
('version_switcher', 'Version Switcher', 'Switch between 10 runtime versions', 'GitBranch', 'explorer', 'runtimes_switched >= 10', 20, 0, 20),
('runtime_master', 'Runtime Master', 'Switch between 100 runtime versions', 'Code', 'master', 'runtimes_switched >= 100', 50, 0, 21),
('security_conscious', 'Security Conscious', 'Generate your first SBOM', 'Shield', 'milestone', 'sbom_generated >= 1', 15, 0, 30),
('security_expert', 'Security Expert', 'Generate 50 SBOMs', 'ShieldCheck', 'master', 'sbom_generated >= 50', 40, 0, 31),
('vulnerability_hunter', 'Vulnerability Hunter', 'Find 10 vulnerabilities', 'Bug', 'special', 'vulnerabilities_found >= 10', 25, 0, 32),
('speed_demon', 'Speed Demon', 'Save 1 hour of time with OMG', 'Zap', 'speed', 'time_saved_ms >= 3600000', 30, 0, 40),
('time_saver', 'Time Saver', 'Save 10 hours of time with OMG', 'Clock', 'speed', 'time_saved_ms >= 36000000', 60, 0, 41),
('productivity_king', 'Productivity King', 'Save 100 hours of time with OMG', 'Crown', 'master', 'time_saved_ms >= 360000000', 150, 0, 42),
('early_adopter', 'Early Adopter', 'Join OMG in its first year', 'Star', 'special', 'created_before:2027-01-01', 50, 0, 100),
('daily_driver', 'Daily Driver', 'Use OMG 30 days in a row', 'Calendar', 'special', 'streak >= 30', 40, 0, 101),
('night_owl', 'Night Owl', 'Run 50 commands after midnight', 'Moon', 'special', 'commands_after_midnight >= 50', 20, 1, 200),
('weekend_warrior', 'Weekend Warrior', 'Run 100 commands on weekends', 'Coffee', 'special', 'weekend_commands >= 100', 20, 1, 201),
('perfectionist', 'Perfectionist', 'Complete all non-hidden achievements', 'Gem', 'special', 'all_achievements_unlocked', 200, 1, 999);
