/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=site/workers/wrangler.toml --include-runtime=false site/workers/worker-configuration.d.ts` (hash: 3bd784ef094cd7b446255a6cf47bcf4c)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ADMIN_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	OFFER_RATE_LIMITER: RateLimit;
	STRIPE_PRO_PRICE_ID: "price_1U7ub2PI6tkdUQScfVcPeLY9";
	STRIPE_TEAM_PRICE_ID: "price_1U7ub3PI6tkdUQScFqTRFgv8";
	STRIPE_INTRO_COUPON_ID: "omg_intro_20_3mo_v1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STRIPE_PRO_PRICE_ID" | "STRIPE_TEAM_PRICE_ID" | "STRIPE_INTRO_COUPON_ID">> {}
}
